version: "3"
services:
  rss:
    image: rss-notify/latest
    build:
      context: .
    container_name: rss-notify
    restart: unless-stopped
    volumes:
      - ./rss-notify-data:/rss-notify-data
    environment:
      - CONFIG_FILE=/rss-notify-data/config.json
      - DATABASE_FILE=/rss-notify-data/db.sqlite
      - UPDATE_INTERVAL_SECONDS=60
      - PUSHOVER_USER
      - PUSHOVER_TOKEN
