version: "3"
services:
  notifeed:
    image: notifeed/latest
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    container_name: notifeed
    restart: unless-stopped
    volumes:
      - ./notifeed-data:/notifeed-data
    environment:
      - CONFIG_FILE=/notifeed-data/config.json
      - READER_DATABASE=/notifeed-data/reader.sqlite
      - PUSHOVER_USER
      - PUSHOVER_TOKEN
